# Generated by Django 4.0.1 on 2022-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
